#!/bin/bash

if [ "$1" = "-h" ]
then
echo "This script determins, whether you are running the script from its home directory"
exit
fi

cur_dir=$(pwd)
script_dir=$(dirname $(readlink -e "$0"))

if [ "$cur_dir" == "$script_dir" ]
then
echo "$script_dir"
exit 0
fi

echo "error: You are not in the home directory"
exit 1

