#!/bin/bash

if [ "$1" = "-h" ] && [ -z "$2" ]
then echo "This script prints out the maximum of 3 integers. Input example: ./max 1 -2 0"
exit
fi

if [ -z "$3" ]
then echo "error: not enough arguments"
exit
fi

if ! [ -z "$4" ]
then echo "error: too many arguments"
exit
fi

regex="-?[0-9]+"
if ! [[ $1 =~ $regex && $2 =~ $regex && $3 =~ $regex ]]
then echo "error: invalid argument(s)"
exit
fi

max=$1

if [ "$2" -ge "$max" ]
then max=$2
fi

if [ "$3" -ge "$max" ]
then max=$3
fi
echo "$max"

